"""
Solutions - Chapter 23: Building Your Own AI Products
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from product_metrics import (
    rank_backlog,
    ltv,
    ltv_cac_ratio,
    cac_payback_months,
    retention_curve,
    funnel_conversion,
    biggest_leak,
)


def test_prioritization():
    backlog = [
        {"name": "high", "reach": 1000, "impact": 3, "confidence": 1.0, "effort": 1},
        {"name": "low", "reach": 1000, "impact": 1, "confidence": 1.0, "effort": 2},
    ]
    ranked = rank_backlog(backlog)
    assert ranked[0][0] == "high", ranked
    return ranked


def test_economics():
    v = ltv(arpu=50, gross_margin=0.8, monthly_churn=0.04)
    ratio = ltv_cac_ratio(v, cac=300)
    payback = cac_payback_months(300, 50, 0.8)
    assert ratio >= 3.0, ratio
    assert payback > 0
    return round(ratio, 2), round(payback, 1)


def test_retention():
    curve = retention_curve(0.1, 6)
    assert curve[0] == 1.0
    assert np.all(np.diff(curve) <= 0)
    return np.round(curve, 3).tolist()


def test_funnel():
    stages = ["visit", "signup", "activate", "subscribe"]
    counts = [10000, 2200, 1300, 420]
    overall, steps = funnel_conversion(counts)
    assert abs(overall - 0.042) < 1e-9
    assert biggest_leak(stages, counts) == "visit -> signup"
    return round(overall, 4)


if __name__ == "__main__":
    print("ranked:", test_prioritization())
    print("ltv:cac, payback:", test_economics())
    print("retention:", test_retention())
    print("funnel overall:", test_funnel())
    print("Chapter 23 solutions: PASS")
