"""
Solutions - Chapter 20: Building Production AI Systems
Generated by Berta AI

Runnable end-to-end (stdlib only). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from reliability import TokenBucket, CircuitBreaker, CircuitOpen, backoff_delays, canary_route
from observability import percentile, golden_signals


def test_rate_limiter():
    tb = TokenBucket(rate=2.0, capacity=3.0)
    allowed = sum(tb.allow(now=0.0) for _ in range(5))
    assert allowed == 3, allowed
    assert tb.allow(now=1.0) is True  # refilled
    return allowed


def test_circuit_breaker():
    cb = CircuitBreaker(fail_threshold=2, reset_timeout=5.0)

    def boom():
        raise ValueError("x")

    for t in range(2):
        try:
            cb.call(boom, now=float(t))
        except ValueError:
            pass
    assert cb.state == "open"
    try:
        cb.call(boom, now=2.0)
        raise AssertionError("should have fast-failed")
    except CircuitOpen:
        pass
    # recovers after timeout via half-open on success
    cb.call(lambda: "ok", now=10.0)
    assert cb.state == "closed"
    return cb.state


def test_backoff():
    d = backoff_delays(0.5, 4)
    assert d == [0.5, 1.0, 2.0, 4.0], d


def test_canary():
    n = 5000
    frac = sum(canary_route(i, 0.2) == "canary" for i in range(n)) / n
    assert abs(frac - 0.2) < 0.02, frac
    assert canary_route(42, 0.2) == canary_route(42, 0.2)
    return round(frac, 3)


def test_signals():
    vals = [10] * 99 + [1000]
    assert percentile(vals, 99) == 10
    sig = golden_signals(vals, errors=1, total=100)
    assert sig["requests"] == 100


if __name__ == "__main__":
    print("rate limiter allowed:", test_rate_limiter())
    print("breaker final state:", test_circuit_breaker())
    test_backoff()
    print("canary fraction:", test_canary())
    test_signals()
    print("Chapter 20 solutions: PASS")
