"""
Solutions - Chapter 17: Advanced RAG & Knowledge Systems
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from hybrid_search import BM25, dense_rank, reciprocal_rank_fusion, rerank
from evaluation import recall_at_k, reciprocal_rank, ndcg_at_k, mean_reciprocal_rank

CORPUS = [
    "training neural networks with gradient descent and backpropagation",
    "the history of the roman empire and its emperors",
    "gradient boosting and decision tree ensembles for tabular data",
    "recipes for baking sourdough bread at home",
    "backpropagation computes gradients via the chain rule",
]


def test_bm25():
    bm25 = BM25(CORPUS)
    ranking = bm25.rank("how does backpropagation work")
    assert ranking[0] in (0, 4), ranking
    return ranking


def test_fusion():
    sparse = [4, 0, 2, 1, 3]
    dense = [0, 4, 2, 3, 1]
    fused = reciprocal_rank_fusion([sparse, dense])
    assert set(fused) == set(range(5))
    assert fused[0] in (0, 4)
    return fused


def test_rerank():
    out = rerank("chain rule", [0, 1, 2, 3, 4], CORPUS)
    assert out[0] == 4, out
    return out


def test_metrics():
    ranking = [4, 2, 0, 1, 3]
    relevant = {4}
    assert recall_at_k(ranking, relevant, 1) == 1.0
    assert reciprocal_rank(ranking, relevant) == 1.0
    assert abs(ndcg_at_k([4, 0, 1], {4}, 3) - 1.0) < 1e-9
    assert abs(mean_reciprocal_rank([[1, 4], [4, 0]], [{4}, {4}]) - 0.75) < 1e-9


if __name__ == "__main__":
    print("bm25:", test_bm25())
    print("fusion:", test_fusion())
    print("rerank:", test_rerank())
    test_metrics()
    print("Chapter 17 solutions: PASS")
