"""
Solutions - Chapter 18: Reinforcement Learning Fundamentals
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from gridworld import GridWorld
from q_learning import train, greedy_policy, run_policy
from config import LAYOUT


def test_value_iteration():
    env = GridWorld(LAYOUT)
    V = env.value_iteration(gamma=0.95)
    assert V[env.start] > 0, V[env.start]
    assert V[env.goal] == 0.0
    return round(V[env.start], 3)


def test_q_learning():
    env = GridWorld(LAYOUT)
    Q, returns = train(env, episodes=800, seed=18)
    policy = greedy_policy(Q)
    steps = run_policy(env, policy)
    assert steps < 100, steps
    # later episodes should on average beat early ones
    assert np.mean(returns[-50:]) > np.mean(returns[:50])
    return steps


def test_discounted_return():
    rewards = [0, 0, 1]
    g = sum((0.9 ** t) * r for t, r in enumerate(rewards))
    assert abs(g - 0.81) < 1e-9
    return g


if __name__ == "__main__":
    print("V(start):", test_value_iteration())
    print("steps to goal:", test_q_learning())
    print("discounted return:", round(test_discounted_return(), 4))
    print("Chapter 18 solutions: PASS")
