"""
Solutions - Chapter 16: Multi-Agent Systems Architecture
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by the validate-chapters
workflow. Notebook solutions live in problem_set_*_solutions.ipynb.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from agents import Agent, contract_net, gossip_consensus, majority_vote
from orchestration import pipeline, supervisor, debate


def test_contract_net():
    agents = [Agent("researcher", 0.9, 1.0), Agent("coder", 0.8, 0.8), Agent("writer", 0.6, 0.4)]
    tasks = [{"id": "survey", "difficulty": 2.0, "min_skill": 0.7}]
    res = contract_net(tasks, agents)
    assert res["survey"] in {"researcher", "coder"}, res
    return res


def test_consensus():
    vals = [10.0, 0.0, 5.0, -3.0]
    A = [[0, 1, 1, 0], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 0]]
    hist = gossip_consensus(vals, A, rounds=300, eps=0.2)
    assert hist[-1].max() - hist[-1].min() < 1e-3
    assert abs(hist[-1].mean() - np.mean(vals)) < 1e-3
    return float(hist[-1].mean())


def test_voting():
    assert majority_vote(["A", "A", "B", "A", "C"]) == "A"


def test_orchestration():
    out, _ = pipeline([str.strip, str.lower], "  HI  ")
    assert out == "hi", out
    results, stats = supervisor({"w": lambda g: g}, ["w"] * 5, "x", max_steps=2)
    assert stats.steps <= 3
    ans, dstats = debate(lambda q: "ok", lambda a: "no", "q", rounds=2)
    assert dstats.steps > 0


if __name__ == "__main__":
    print("contract-net:", test_contract_net())
    print("consensus mean:", round(test_consensus(), 4))
    test_voting()
    test_orchestration()
    print("Chapter 16 solutions: PASS")
