"""Configuration for Chapter 20: Production AI Systems."""

SLO_LATENCY_MS_P99 = 250.0
SLO_AVAILABILITY = 0.999

RATE_LIMIT_PER_SEC = 10.0
RATE_LIMIT_BURST = 20.0

BREAKER_FAIL_THRESHOLD = 3
BREAKER_RESET_TIMEOUT_S = 5.0
