"""
Solutions - Chapter 24: Research & Cutting-Edge Techniques
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from attention import softmax, scaled_dot_product_attention, causal_mask
from moe import top_k_gating, moe_forward


def test_softmax():
    p = softmax(np.array([[2.0, 1.0, 0.1], [0.0, 0.0, 0.0]]), axis=1)
    assert np.allclose(p.sum(axis=1), 1.0)
    assert (p >= 0).all()
    return p.shape


def test_attention():
    rng = np.random.default_rng(24)
    out, attn = scaled_dot_product_attention(
        rng.standard_normal((3, 8)),
        rng.standard_normal((5, 8)),
        rng.standard_normal((5, 4)),
    )
    assert out.shape == (3, 4)
    assert np.allclose(attn.sum(axis=1), 1.0)
    # causal mask blocks the future
    n = 5
    _, am = scaled_dot_product_attention(
        rng.standard_normal((n, 8)), rng.standard_normal((n, 8)),
        rng.standard_normal((n, 4)), mask=causal_mask(n),
    )
    assert np.allclose(np.triu(am, k=1), 0.0, atol=1e-6)
    return out.shape


def test_moe():
    rng = np.random.default_rng(24)
    x = rng.standard_normal((4, 16))
    W = rng.standard_normal((16, 4))
    idx, w = top_k_gating(x, W, k=2)
    assert idx.shape == (4, 2)
    assert np.allclose(w.sum(axis=1), 1.0)
    experts = [lambda x, s=s: x * s for s in (1.0, 2.0, 3.0, 4.0)]
    y, _, _ = moe_forward(x, W, experts, k=2)
    assert y.shape == (4, 16)
    return y.shape


if __name__ == "__main__":
    print("softmax shape:", test_softmax())
    print("attention shape:", test_attention())
    print("moe shape:", test_moe())
    print("Chapter 24 solutions: PASS")
