"""
Solutions - Chapter 25: AI Governance & Ethics
Generated by Berta AI

Runnable end-to-end (stdlib only). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from governance import classify_risk, generate_model_card, validate_model_card, risk_matrix
from config import REQUIRED_CARD_FIELDS


def test_risk_tiers():
    assert classify_risk({"domain": "employment"}) == "high"
    assert classify_risk({"domain": "support", "generates_content": True}) == "limited"
    assert classify_risk({"prohibited": True}) == "unacceptable"
    assert classify_risk({"domain": "email"}) == "minimal"
    return "ok"


def test_risk_matrix():
    assert risk_matrix(1, 1) == "low"
    assert risk_matrix(3, 3) == "medium"
    assert risk_matrix(4, 3) == "high"
    assert risk_matrix(5, 5) == "critical"
    return "ok"


def test_model_card():
    meta = {f: f"value for {f}" for f in REQUIRED_CARD_FIELDS}
    card = generate_model_card(meta)
    for f in REQUIRED_CARD_FIELDS:
        assert f.replace("_", " ").title() in card
    assert validate_model_card(meta)["complete"]
    bad = validate_model_card({"model_name": "X"})
    assert not bad["complete"] and "metrics" in bad["missing"]
    return "ok"


if __name__ == "__main__":
    print("risk tiers:", test_risk_tiers())
    print("risk matrix:", test_risk_matrix())
    print("model card:", test_model_card())
    print("Chapter 25 solutions: PASS")
