"""
Solutions - Chapter 21: AI for Finance
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from metrics import simple_returns, sharpe_ratio, equity_curve, max_drawdown
from backtest import ma_crossover_signal, backtest


def test_metrics():
    prices = [100, 101.2, 100.5, 102.1, 103.4, 102.8, 104.6, 105.9, 105.1, 106.7]
    r = simple_returns(prices)
    eq = equity_curve(r)
    assert max_drawdown(eq) <= 0.0
    steady, volatile = [0.012, 0.011, 0.013, 0.010, 0.012], [0.05, -0.03, 0.04, -0.02, 0.01]
    assert sharpe_ratio(steady) > sharpe_ratio(volatile)
    return round(sharpe_ratio(r), 3)


def test_backtest():
    prices = [100, 101, 102, 101, 103, 105, 104, 106, 108, 107]
    sig = ma_crossover_signal(prices, fast=3, slow=5)
    res = backtest(prices, sig, cost_per_trade=0.0005)
    assert (res["equity"] > 0).all()
    assert res["max_drawdown"] <= 0.0
    return round(res["total_return"], 4)


def test_costs_reduce_return():
    prices = [100, 102, 101, 104, 103, 106, 105, 108]
    sig = ma_crossover_signal(prices)
    free = backtest(prices, sig, 0.0)["total_return"]
    costly = backtest(prices, sig, 0.001)["total_return"]
    assert costly <= free + 1e-12
    return round(free - costly, 5)


def test_no_lookahead():
    prices = [100, 101.2, 100.5, 102.1, 103.4, 102.8, 104.6, 105.9, 105.1, 106.7]
    sig = ma_crossover_signal(prices)
    rets = simple_returns(prices)
    honest = float((rets * np.asarray(sig, float)[:-1]).sum())
    cheating = float((rets * np.asarray(sig, float)[1:]).sum())
    assert honest != cheating
    return round(honest, 4)


if __name__ == "__main__":
    print("Sharpe:", test_metrics())
    print("backtest total return:", test_backtest())
    print("cost drag:", test_costs_reduce_return())
    print("honest return:", test_no_lookahead())
    print("Chapter 21 solutions: PASS")
