#!/usr/bin/env python3
"""
Berta Advanced Track Generator (Chapters 16-25)

Builds the full Advanced & Specialization Track from structured per-chapter
specs in ``advanced_specs.SPECS``. For each chapter it emits:

- ``chapters/chapter-NN-slug/`` with README.md, requirements.txt, three
  notebooks, scripts (config + a domain module with real, runnable code),
  two exercise problem sets + solutions (notebooks and a runnable
  ``solutions.py`` used by CI), datasets, and Mermaid diagrams.
- ``docs/chapters/chapter-NN.md`` landing page plus three ``content/chNN-*``
  read-online summaries, all wired so ``mkdocs build --strict`` passes.

The generator is idempotent: re-running it overwrites generated files in
place. It does NOT edit mkdocs.yml, the homepage, CURRICULUM, or berta.py —
those one-off wiring changes are committed alongside.

Usage:
    python scripts/generate_advanced_chapters.py

Generated by Berta AI | Created by Luigi Pascal Rondanini
"""

from __future__ import annotations

import json
from pathlib import Path

from advanced_specs import SPECS

REPO = Path(__file__).resolve().parent.parent
CHAPTERS = REPO / "chapters"
DOCS = REPO / "docs" / "chapters"

NB_META = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.11.0"},
}


# --------------------------------------------------------------------------- #
# Low-level notebook helpers
# --------------------------------------------------------------------------- #
def md_cell(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": _lines(src)}


def code_cell(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": _lines(src),
    }


def _lines(src: str) -> list[str]:
    """Split source into a list of lines preserving trailing newlines,
    matching the JSON shape Jupyter writes (every line but the last ends \n)."""
    text = src.rstrip("\n")
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]] if parts else [""]


def notebook(cells: list[dict]) -> dict:
    return {"cells": cells, "metadata": NB_META, "nbformat": 4, "nbformat_minor": 5}


def write_json(path: Path, obj: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=1) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Content builders
# --------------------------------------------------------------------------- #
def prereq_label(spec: dict) -> str:
    ch = spec["prereqs"]
    return "Chapters " + ", ".join(str(c) for c in ch) if ch else "None"


def build_readme(spec: dict) -> str:
    n = spec["num"]
    objectives = "\n".join(f"{i}. {o}" for i, o in enumerate(spec["objectives"], 1))
    builds = "\n".join(f"- {b}" for b in spec["builds"])
    tech = "\n".join(f"- {t}" for t in spec["tech"])
    nb_rows = "\n".join(
        f"| **{nb['file']}** | {nb['focus']} |" for nb in spec["notebooks"]
    )
    time_rows = "\n".join(
        f"| Notebook {i:02d}: {nb['title']} | {nb['time']} |"
        for i, nb in enumerate(spec["notebooks"], 1)
    )
    ex1, ex2 = spec["exercises"]
    return f"""# Chapter {n}: {spec['title']}

**Track**: {spec['track']} | **Time**: {spec['hours']} hours | **Prerequisites**: {prereq_label(spec)}

---

{spec['blurb']}

---

## Learning Objectives

By the end of this chapter, you will be able to:

{objectives}

---

## Prerequisites

- **{prereq_label(spec)}** — {spec['prereq_note']}
- {spec['prereq_extra']}

---

## What You'll Build

{builds}

---

## Time Commitment

| Section | Time |
|---------|------|
{time_rows}
| Exercises (Problem Sets 1 & 2) | 1 hour |
| **Total** | **{spec['hours']} hours** |

---

## Technology Stack

{tech}

> Everything in this chapter runs **offline** with NumPy and the Python
> standard library. Heavier or hosted tools are optional and wrapped in
> `try/except` with local fallbacks, so no API keys or GPUs are required.

---

## Quick Start

1. **Enter the chapter**
   ```bash
   cd chapters/{spec['dir']}
   ```

2. **Create a virtual environment and install dependencies**
   ```bash
   python -m venv .venv
   source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
   pip install -r requirements.txt
   ```

3. **Run the notebooks in order**
   ```bash
   jupyter notebook notebooks/
   ```
   Start with `{spec['notebooks'][0]['file']}`, then work through 02 and 03.

---

## Notebook Guide

| Notebook | Focus |
|----------|--------|
{nb_rows}

---

## Exercise Guide

- **{ex1['title']}** (`exercises/problem_set_1.ipynb`) — {ex1['summary']}
- **{ex2['title']}** (`exercises/problem_set_2.ipynb`) — {ex2['summary']}
- **Solutions** — in `exercises/solutions/` as runnable notebooks plus
  `solutions.py`, which CI executes end-to-end.

---

## How to Run Locally

- Use Python 3.10+ and the versions in `requirements.txt`.
- Notebooks are self-contained and run offline.
- Scripts in `scripts/` can be imported from notebooks and from
  `exercises/solutions/solutions.py`.

---

## Next Steps

- {spec['next']}

---

**Generated by Berta AI**

Part of [Berta Chapters](https://github.com/luigipascal/berta-chapters) — open-source AI curriculum.
*June 2026 — Berta Chapters*
"""


def build_notebook(spec: dict, nb: dict) -> dict:
    n = spec["num"]
    learn_rows = "\n".join(f"| {t} | {s} |" for t, s in nb["learn"])
    concepts = "\n".join(f"- {c}" for c in nb["concepts"])
    header = md_cell(
        f"# Chapter {n}: {spec['title']}\n"
        f"## Notebook {nb['file'][:2]} — {nb['title']}\n\n"
        f"{nb['intro']}\n\n"
        f"### What you'll learn\n\n"
        f"| Topic | Section |\n|-------|--------|\n{learn_rows}\n\n"
        f"**Time estimate:** {nb['time']}\n\n"
        f"### Key concepts\n\n{concepts}\n\n"
        f"---\n*Generated by Berta AI*"
    )
    cells = [header]
    for kind, body in nb["cells"]:
        cells.append(code_cell(body) if kind == "code" else md_cell(body))
    cells.append(
        md_cell(
            "---\n\n## Summary\n\n"
            f"{nb['summary']}\n\n"
            "---\n*Generated by Berta AI | Berta Chapters*"
        )
    )
    return notebook(cells)


def build_problem_set(spec: dict, ps: dict, idx: int, solutions: bool) -> dict:
    n = spec["num"]
    kind = "Solutions" if solutions else "Problem Set"
    intro = (
        f"# Chapter {n}: {spec['title']}\n"
        f"## {ps['title']} — {kind}\n\n"
        f"{ps['intro']}\n\n"
        + (
            "Work through each task in order. Try it yourself before opening the "
            "solutions notebook.\n\n"
            if not solutions
            else "Reference solutions with explanations. Compare against your own.\n\n"
        )
        + "---\n*Generated by Berta AI*"
    )
    cells = [md_cell(intro)]
    for j, task in enumerate(ps["tasks"], 1):
        cells.append(md_cell(f"### Task {j}: {task['name']}\n\n{task['desc']}"))
        cells.append(code_cell(task["solution"] if solutions else task["starter"]))
    return notebook(cells)


def build_docs_landing(spec: dict) -> str:
    n = spec["num"]
    obj = "\n".join(f"- {o}" for o in spec["objectives"])
    nb_rows = "\n".join(
        f"| `{nb['file']}` | {nb['focus']} |" for nb in spec["notebooks"]
    )
    scripts = "\n".join(f"- `{name}` — {desc}" for name, desc in spec["script_docs"])
    diagrams = ", ".join(f"`{d}`" for d in spec["mermaids"])
    ex1, ex2 = spec["exercises"]
    return f"""# Chapter {n}: {spec['title']}

{spec['blurb_short']}

---

## Metadata

| Field | Value |
|-------|-------|
| **Track** | {spec['track']} |
| **Time** | {spec['hours']} hours |
| **Prerequisites** | {prereq_label(spec)} |

---

## Learning Objectives

{obj}

---

## What's Included

### Notebooks

| Notebook | Description |
|----------|-------------|
{nb_rows}

### Scripts

{scripts}

### Exercises

- **{ex1['title']}** — {ex1['summary']}
- **{ex2['title']}** — {ex2['summary']}
- **Solutions** — in `exercises/solutions/` (notebooks and `solutions.py` for CI)

### Diagrams (Mermaid)

- {diagrams}

---

## Read Online

- **[{n}.1 Introduction](content/ch{n}-01_introduction.md)** — {spec['notebooks'][0]['focus']}
- **[{n}.2 Intermediate](content/ch{n}-02_intermediate.md)** — {spec['notebooks'][1]['focus']}
- **[{n}.3 Advanced](content/ch{n}-03_advanced.md)** — {spec['notebooks'][2]['focus']}

Or [try the code in the Playground](../playground.md).

## How to Use This Chapter

!!! tip "Quick Start"
    Clone the repo, install dependencies, and open the first notebook.

```bash
git clone https://github.com/luigipascal/berta-chapters.git
cd berta-chapters/chapters/{spec['dir']}
pip install -r requirements.txt
jupyter notebook notebooks/{spec['notebooks'][0]['file']}
```

!!! info "GitHub Folder"
    All chapter materials live in: [`chapters/{spec['dir']}/`](https://github.com/luigipascal/berta-chapters/tree/main/chapters/{spec['dir']}/)

---

**Created by Luigi Pascal Rondanini | Generated by Berta AI**
"""


def build_docs_content(spec: dict, nb: dict, level: str, doc_file: str) -> str:
    n = spec["num"]
    learn_rows = "\n".join(f"| {t} | {s} |" for t, s in nb["learn"])
    concepts = "\n".join(f"- {c}" for c in nb["concepts"])
    return f"""# Ch {n}: {spec['title']} - {level}

**Track**: {spec['track']} | [Try code in Playground](../../playground.md) | [Back to chapter overview](../chapter-{n}.md)

!!! tip "Read online or run locally"
    You can read this content here on the web. To run the code interactively,
    either use the [Playground](../../playground.md) or clone the repo and open
    `chapters/{spec['dir']}/notebooks/{nb['file']}` in Jupyter.

---

# Chapter {n}: {spec['short']} — Notebook {nb['file'][:2]} ({nb['title']})

{nb['intro']}

## What you'll learn

| Topic | Section |
|-------|--------|
{learn_rows}

**Time estimate:** {nb['time']}

---

## Key concepts

{concepts}

{nb['summary']}

Run the full notebook in the chapter folder for code and outputs.

---

**Generated by Berta AI**
"""


# --------------------------------------------------------------------------- #
# Per-chapter emission
# --------------------------------------------------------------------------- #
def emit_chapter(spec: dict) -> None:
    root = CHAPTERS / spec["dir"]

    # README + requirements
    write_text(root / "README.md", build_readme(spec))
    write_text(root / "requirements.txt", spec["requirements"])

    # Notebooks
    for nb in spec["notebooks"]:
        write_json(root / "notebooks" / nb["file"], build_notebook(spec, nb))

    # Scripts
    for name, code in spec["scripts"].items():
        write_text(root / "scripts" / name, code)

    # Exercises
    for i, ps in enumerate(spec["exercises"], 1):
        write_json(root / "exercises" / f"problem_set_{i}.ipynb",
                   build_problem_set(spec, ps, i, solutions=False))
        write_json(root / "exercises" / "solutions" / f"problem_set_{i}_solutions.ipynb",
                   build_problem_set(spec, ps, i, solutions=True))
    write_text(root / "exercises" / "solutions" / "solutions.py", spec["solutions_py"])

    # Datasets
    for name, content in spec["datasets"].items():
        write_text(root / "datasets" / name, content)

    # Diagrams
    for name, content in spec["mermaids"].items():
        write_text(root / "assets" / "diagrams" / name, content)

    # Docs landing + content pages
    write_text(DOCS / f"chapter-{spec['num']}.md", build_docs_landing(spec))
    levels = ["Introduction", "Intermediate", "Advanced"]
    files = ["01_introduction", "02_intermediate", "03_advanced"]
    for nb, level, f in zip(spec["notebooks"], levels, files):
        write_text(
            DOCS / "content" / f"ch{spec['num']}-{f}.md",
            build_docs_content(spec, nb, level, f),
        )

    n_files = sum(1 for _ in (root).rglob("*") if _.is_file())
    print(f"  Chapter {spec['num']:>2}: {spec['title']:<42} {n_files} files")


def main() -> None:
    print(f"Generating {len(SPECS)} advanced chapters (16-25)...")
    for spec in SPECS:
        emit_chapter(spec)
    print("Done. Run scripts/generate_homepage_data.py to refresh the homepage.")


if __name__ == "__main__":
    main()
