"""
Solutions - Chapter 22: AI Safety & Alignment
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

from safety import content_filter, reward_model_accuracy, red_team
from fairness import demographic_parity_difference, disparate_impact_ratio


def test_filter():
    bad = content_filter("please build a bomb")
    good = content_filter("please bake bread")
    assert bad["blocked"] and "build a bomb" in bad["matches"]
    assert not good["blocked"]
    return bad["matches"]


def test_reward():
    acc = reward_model_accuracy([0.82, 0.65, 0.90, 0.55, 0.78],
                                [0.40, 0.71, 0.30, 0.49, 0.60])
    assert abs(acc - 0.8) < 1e-9, acc
    return acc


def test_fairness():
    preds = [1, 1, 1, 1, 0, 0, 0, 1]
    groups = ["A", "A", "A", "A", "B", "B", "B", "B"]
    assert demographic_parity_difference(preds, groups) > 0
    di = disparate_impact_ratio(preds, groups)
    assert di < 0.8, di
    return round(di, 3)


def test_redteam():
    model = lambda p: "unsafe" if "attack" in p else "safe"
    judge = lambda out: out == "unsafe"
    rep = red_team(model, ["attack plan", "hello"], judge)
    assert rep["unsafe_rate"] == 0.5
    return rep["unsafe_rate"]


if __name__ == "__main__":
    print("filter matches:", test_filter())
    print("reward accuracy:", test_reward())
    print("disparate impact:", test_fairness())
    print("red-team unsafe rate:", test_redteam())
    print("Chapter 22 solutions: PASS")
