"""
Solutions - Chapter 19: Model Optimization & Inference
Generated by Berta AI

Runnable end-to-end (NumPy + stdlib). Exercised by validate-chapters.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import numpy as np
from optimize import (
    quantize_int8,
    quantization_error,
    magnitude_prune,
    measure_sparsity,
    softmax_with_temperature,
    model_size_bytes,
)
from inference import batch_latency, throughput


def test_quantization():
    rng = np.random.default_rng(19)
    W = rng.standard_normal((16, 16))
    _, scale = quantize_int8(W)
    err = quantization_error(W)
    assert err <= scale / 2 + 1e-9, (err, scale)
    return round(err, 5)


def test_pruning():
    rng = np.random.default_rng(7)
    W = rng.standard_normal((20, 20))
    Wp = magnitude_prune(W, 0.6)
    assert abs(measure_sparsity(Wp) - 0.6) <= 0.005
    return measure_sparsity(Wp)


def test_distillation():
    logits = np.array([6.0, 2.0, 1.0])
    hot = softmax_with_temperature(logits, 1.0)
    soft = softmax_with_temperature(logits, 4.0)
    assert abs(soft.sum() - 1.0) < 1e-9
    assert soft.max() < hot.max()


def test_inference():
    assert model_size_bytes(1_000_000, "float32") == 4_000_000
    assert throughput(128) > throughput(1)
    assert batch_latency(128) > batch_latency(1)


if __name__ == "__main__":
    print("quant error:", test_quantization())
    print("sparsity:", test_pruning())
    test_distillation()
    test_inference()
    print("Chapter 19 solutions: PASS")
